### ISSUE TITLE
Object Reference In DocumentQueryResuslt

### ISSUE THREAD

**Issue by behzad888** [DocuWare/Platform.NETClient#1]
Hope you doing well,

I have an error on [this line](https://github.com/DocuWare/Platform.NETClient/blob/2c4495f6d6f85b0e10a3329c192e1a1dd63d9ec1/src/PlatformClient.cs#L437). Query is null even after SelfRelation.

any idea?

Docuware v7.0

**Comment by DocuWareFM** [comment]
Hi @behzad888, 
sry for late answer but can you post the error message for better investigation?
That will help a lot.
