### ISSUE TITLE
How to programatically fill DialogExpression

### ISSUE THREAD

**Issue by SebastianSchultz** [DocuWare/Platform.NETClient#2]
Hello,

I want to fill the DialogExpression for a search programatically from a DataGridView:

```cs
foreach (DataGridViewRow row in dgvFieldEntries.Rows)
{
	if (!row.IsNewRow)
	{
		GlobalVar.SearchConditions = new List<DialogExpressionCondition>()
		{
			DialogExpressionCondition.Create(fieldName: row.Cells["Field"].Value.ToString(), value: row.Cells["Value"].Value.ToString()),
		};
	}
}
```

But that doesn't work.
I only get the first entry of the DataGridView as Search criteria.

Can somebody help?

**Comment by alexo9** [comment]
You are recreating SearchConditions on each loop.

**Comment by SebastianSchultz** [comment]
Yepp, thanks I found my mistake :)
