### ISSUE TITLE
Cannot get workflow names

### ISSUE THREAD

**Issue by SebastianSchultz** [DocuWare/Platform.NETClient#3]
Hello,

I try to get ll workflow names with the following code:

```csharp
var org = conn.Organizations[0];
richTextBox.Clear();
var myWorkflows = org.GetWorkflowsFromWorkflowsRelation();
foreach (var workflow in myWorkflows.Workflow)
	richTextBox.AppendText("\r\n Workflow Name: " + workflow.Name);
```

But when I execute this code, nothing happens e.g. the richtTextBox stays empty.
The connection is ok cause I can get all cabinets, dialogs and so on.

What am I'm doing wrong?

**Comment by DocuWareFM** [comment]
Hi @SebastianSchultz,
Is any workflow active because it only displays active workflows?

**Comment by SebastianSchultz** [comment]
Ah ok, my fault. I didn't know that only active workflows can be displayed.
Thatk you very much for help!
