### ISSUE TITLE
Update Select Lists programmatically

### ISSUE THREAD

**Issue by LucasKrmpotic** [DocuWare/Platform.NETClient#4]
We need to know if it is possible update a Select List programmatically from .NET sdk. 
Do you have any code example? 
Thanks.

**Comment by alexo9** [comment]
Hey Lucas, looks like you might be able to set the Value property of the SingleColumnSelectListValues class.  looks like a List<string>, but i don't see an endpoint to post that to.

https://developer.docuware.com/dotNet_API_Reference/PlatformServerClient/DocuWare.Platform.ServerClient.SingleColumnSelectListValues.html#methods

**Comment by alexo9** [comment]
if I do a postman on saving a select list in the app, it looks it posts to an ajax endpoint... must not be in the sdk.

/DocuWare/Settings/SettingsService.svc/ajax/SaveSelectList

this is the JSON that was posted in the body, maybe you can do something with that:

{
    "session": {
        "SessionID": "***",
        "Organization": "***",
        "OrganizationGuid": "***",
        "User": "alex",
        "UserGuid": "***"
    },
    "data": {
        "__type": "FixedSelectList:http://dev.docuware.com/settings/organization",
        "Header": {
            "Guid": "3abda781-7096-4109-b8fa-7d95d9bcd708",
            "ID": 731,
            "Name": "Expense Categories",
            "IsMultiField": false,
            "Type": 1
        },
        "Columns": [
            "SingleSelectList"
        ],
        "Entries": [
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "6th"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "7th"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "Entertainment"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "fifth one"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "Food"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "Miscellaneous"
            },
            {
                "__type": "SingleFieldSelectListEntry:http://dev.docuware.com/settings/organization",
                "Value": "Travel"
            }
        ]
    },
    "flags": 1
}

**Comment by DocuWareFM** [comment]
The SettingsService isn't part of our official public SDK API and shouldn't be used in any case.
Because the API isn't meant to be stable over versions.

If you want that feature in the future go to https://docuware.uservoice.com/ and create or vote for a existing user voice.
