### ISSUE TITLE
Automatically move document from basket to cabinet if Intellix is green

### ISSUE THREAD

**Issue by SebastianSchultz** [DocuWare/Platform.NETClient#5]
I want to move a document from a basket to a cabinet if Intellix is green.

I use the following code:

`        private void btnStart_Click(object sender, EventArgs e)
        {
            btnStart.Enabled = false;
            rtbMain.Clear();
            GlobalVar.DocuwareURL = new Uri(tbURL.Text + @"/DocuWare/Platform/");
            GlobalVar.DocuwareUser = tbUsername.Text;
            GlobalVar.DocuwarePassword = tbPassword.Text;
            GlobalVar.DocuwareBasketGUID = tbBasketGUID.Text;
            GlobalVar.DocuwareArchiveGUID = tbDocuwareArchiveGUID.Text;
            GlobalVar.Connection = ServiceConnection.Create(GlobalVar.DocuwareURL, GlobalVar.DocuwareUser, GlobalVar.DocuwarePassword);
            GlobalVar.Organisation = GlobalVar.Connection.Organizations[0];

            FileCabinet DWBasket = GlobalVar.Organisation.GetFileCabinetsFromFilecabinetsRelation().FileCabinet.FirstOrDefault(fc => fc.Id == GlobalVar.DocuwareBasketGUID);
            FileCabinet DWArchive = GlobalVar.Organisation.GetFileCabinetsFromFilecabinetsRelation().FileCabinet.FirstOrDefault(fc => fc.Id == GlobalVar.DocuwareArchiveGUID);
            if ((DWBasket != null) && (DWArchive != null))
            {
                DocumentsQueryResult allDocumentsOfBasket = GlobalVar.Connection.GetFromDocumentsForDocumentsQueryResultAsync(GlobalVar.DocuwareBasketGUID).Result;
                List<int> documentIDs = new List<int>();
                foreach (var document in allDocumentsOfBasket.Items)
                {
                    switch (document.IntellixTrust)
                    {
                        case IntellixTrust.Green:
                            documentIDs.Add(document.Id);
                            if (documentIDs.Count > 0)
                            {
                                StoreIfIntellixIsGreen(document, DWBasket, DWArchive);
                            }
                        break;
                       
                        default:
                            rtbMain.AppendText("\r\n" + "Skipping: " + document.Title\r\n");
                            rtbMain.ScrollToCaret();
                        break;
                    }
                }
            }
            btnStart.Enabled = true;
        }
`

I declared "StoreIfIntellixIsGreen" as follows:

`		public DocumentsQueryResult StoreIfIntellixIsGreen(Document document, FileCabinet documentTray, FileCabinet fileCabinet)
        {
            var transferInfo = new FileCabinetTransferInfo()
            {
                KeepSource = true,
                SourceDocId = new List<int> { document.Id },
                SourceFileCabinetId = documentTray.Id,
                FillIntellix = true
            };
            return fileCabinet.PostToTransferRelationForDocumentsQueryResult(transferInfo);
        }`

But when I execute, the green documents are copied without any index data.
How can I copy the documents with the Intellix index data?

**Comment by alexo9** [comment]
Looks right to me.  Is the default store dialog of the tray the Intellix dialog for the file cabinet fileCabinet?  If not, it would still store them, but would not fill the index values.

**Comment by SebastianSchultz** [comment]
I have only one store dialog in this archive.

**Comment by alexo9** [comment]
I captured a request from the user interface to Store Automatically from postman, and compared it to the request my console application was making, and it's isn't the same.  I tried using DocumentTransferInfo instead of FileCabinetTransferInfo, and got the same results.  I made a couple of changes to your code to make it make a little more sense, and sent it on to the docuware support group as a bug.  They will confirm and get an ETA on fixing it.
        
        public List<int> AutoStoreGreens()
        {
            var tray = doc.getFilecab(_trayID);
            var fc = doc.getFilecab(_fCID);
            DocumentsQueryResult allDocumentsOfBasket = tray.GetDocumentsQueryResultFromDocumentsRelation();
            List<int> documentIDs = new List<int>();
            foreach (var document in allDocumentsOfBasket.Items)
            {
                switch (document.IntellixTrust)
                {
                    case IntellixTrust.Green:
                        documentIDs.Add(document.Id);
                        break;

                    default:
                        break;
                }
            }

            if (documentIDs.Count > 0)
            {
                allDocumentsOfBasket = doc.StoreWithIntellix(documentIDs,tray,fc);
            }


            return documentIDs;
        }


        public DocumentsQueryResult StoreWithIntellix(List<int> documents, FileCabinet documentTray, FileCabinet fileCabinet) 
        {
            var transferInfo = new FileCabinetTransferInfo() 
            {
                SourceFileCabinetId = documentTray.Id,
                KeepSource = true,
                SourceDocId = documents,
                FillIntellix = true
            }; 
            return fileCabinet.PostToTransferRelationForDocumentsQueryResult(transferInfo); 
        }

**Comment by SebastianSchultz** [comment]
Can you update me here if you have news about it?

**Comment by alexo9** [comment]
ok, so looks like the issue is that the Transfer needs to come from the store dialog, not the file cabinet.  This worked for me.

        public DocumentsQueryResult StoreWithIntellix(List<int> documents, FileCabinet documentTray, FileCabinet fileCabinet) 
        {
            var dial = GetStoreDialog(documentTray.AssignedCabinetId, documentTray.IntellixDialogId);
            var transferInfo = new FileCabinetTransferInfo() 
            {
                SourceFileCabinetId = documentTray.Id,
                KeepSource = true,
                SourceDocId = documents,
                FillIntellix = true
            }; 
            return dial.PostToTransferRelationForDocumentsQueryResult(transferInfo); 
        }

**Comment by alexo9** [comment]
or a little clearer:

        public DocumentsQueryResult StoreWithIntellix(List<int> documents, FileCabinet documentTray, FileCabinet fileCabinet) 
        {
            var dialogInfos = fileCabinet.GetDialogInfosFromStoresRelation();
            var dialoginfo = dialogInfos.Dialog.FirstOrDefault(d => d.Id == documentTray.IntellixDialogId);
            var dial = dialoginfo.GetDialogFromSelfRelation();

            var transferInfo = new FileCabinetTransferInfo() 
            {
                SourceFileCabinetId = documentTray.Id,
                KeepSource = true,
                SourceDocId = documents,
                FillIntellix = true
            }; 
            return dial.PostToTransferRelationForDocumentsQueryResult(transferInfo); 
        }

**Comment by SebastianSchultz** [comment]
Perfect, that works fine :)

Thank you in advance for your help.
