### ISSUE TITLE
How to set a stamp on a documents free place

### ISSUE THREAD

**Issue by SebastianSchultz** [DocuWare/Platform.NETClient#6]
Hey everybody,

Is it possible to set a specific stamp on the first page of a document?
In my code I query documents by index fields. How can I set a stamp on this documents list?

The example on the developer site doesn't work for me?! Here I have to set a page for the stamp.

**Comment by DocuWareFM** [comment]
Hi @SebastianSchultz,
Look at that examples https://github.com/DocuWare/Examples-dotNetCore/blob/master/Examples/Document/StampsAndAnnotations.cs here you should find what you need.
Don't worry about DotNet Core it should be really similar to the DotNet Framework code.
Also it can be used in newer DotNet versions like 6 or 7.

**Comment by SebastianSchultz** [comment]
Hi @DocuWareFM .

I have the following code.
`
       public static void SetStampOnPageWithBestPosition(Document document, string stampID, string sectionID, int layer, string stampTextValue)
            
        {
            DWPoint bestPosition;

            if (document == null)
            {
                MessageBox.Show("Document is null!");
            }
            else
            {
                document = document.GetDocumentFromSelfRelation();
                Section section = document.Sections.FirstOrDefault(s => s.Id == sectionID);
                if (section == null)
                {
                    MessageBox.Show("Section is null");
                }
                else
                {
                    section = section.GetSectionFromSelfRelation();
                    Page page = section.Pages.GetPagesFromNextBlockRelation().Page.FirstOrDefault();
                    if (page == null)
                    {
                        MessageBox.Show("Page is null!");
                    }
                    else
                    {
                        bestPosition = page.PostToStampBestPositionRelationForDWPoint(new StampFormFieldValues() { StampId = stampID });
                        if (bestPosition == null)
                        {
                            MessageBox.Show("BestPositon is null!");
                        }
                        else
                        {
                            StampPlacement stampPlacement = new StampPlacement()
                            {
                                StampId = stampID,
                                Layer = layer,
                                Location = bestPosition,
                                Field = new List<FormFieldValue>()
                                {
                                    new FormFieldValue()
                                    {
                                        Name = "<#1>",
                                        TypedValue = new DocumentIndexFieldValue()
                                        {
                                            ItemElementName = ItemChoiceType.String,
                                            Item = stampTextValue
                                        }
                                    }
                                }
                            };
                            Annotation annotation = page.PostToStampRelationForAnnotation(stampPlacement);
                        }
                    }
                }
            }
        }`


I run it with my document object:

`
               SetStampOnPageWithBestPosition(document, "7876f88d-6b76-4c3c-afb6-7af5df823cc6", "1-1", 1, "This is a test");
`

If I run it I get the message "section is null" ?!

**Comment by DocuWareFM** [comment]
Does the Document have a section with the id 1-1?
The section id have a own count for the second number after the hyphen so it could be that it is for example 1-42.

If you have further questions contact our support at support.docuware.com or visit our user forum https://support.docuware.com/en-US/forums/

This are our official channels for that kind of request.
I close this issue now and have a good one.
